### ISSUE TITLE
Open in External media player - Does nothing

### ISSUE THREAD

**Issue by lamyergeier** [7dJx1qP/stash-plugins#10]
```
$ type python
python is /usr/bin/python
$ python --version
Python 3.12.3
```

# Set it to vlc

```
$ type vlc
vlc is /usr/bin/vlc
```

![image](https://github.com/7dJx1qP/stash-plugins/assets/42092626/5f06bae6-c0ec-468c-aa8a-1e3514de09a8)

# Clicked on Path URl

![image](https://github.com/7dJx1qP/stash-plugins/assets/42092626/79b93815-17bb-4624-afda-7b3ac75c43e1)

# NOTHING happens!

**Comment by Soulcrzkc** [comment]
Me too. Perhaps it only works on the server where stash.exe is located, and the client that connects to stash through the network does not work?

**Comment by oryxcallotis** [comment]
For what little it's worth, I have this installed on Windows on my own PC. If using MPC-HC, it opens the program but with no video. If using VLC, it does open for me, and plays the video properly. File path is simply 

`C:\Program Files\VideoLAN\VLC\vlc.exe`

I also thought this was broken for me because I use MPC-HC by default, and tried for 5 minutes to get it working. VLC just worked immediately after pasting the file path.
